#
# Executes commands at the start of an interactive session.

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.prezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.prezto/init.zsh"
fi

# on OSX, fix the broken(?) LC_CTYPE setting
if [[ $(uname -s) = "Darwin" && $LC_CTYPE = "UTF-8" ]]; then
    LC_CTYPE="en_US.UTF-8"
fi

if [[ -s $HOME/.scm_breeze/scm_breeze.sh ]]; then
    source "$HOME/.scm_breeze/scm_breeze.sh"
fi

source ~/.common_env
